<<<<<<< HEAD
<<<<<<< HEAD
name: Continuous Integration and Deployment

on:
=======
>>>>>>> d4a28ab4d8efa24c54acc6672c01056f0f805d89
=======
name: Continuous Integration and Deployment

on:
>>>>>>> 6d726728ce2f75b89df20f6c896ed8d129cb6aff
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Replace with the Python version you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Run bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: python bot.py
